# Make sure to check the documentation at http://goreleaser.com
project_name: gobble

before:
  hooks:
  - go mod download

builds:
- goos:   [linux]
  goarch: [amd64]
  env:
  - CGO_ENABLED=1

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^pkg:'
